### PR TITLE
Cleanups

### PR DESCRIPTION
**Pull request by diasjorge**
I ran the project through pylint and found many warnings.

I tried to fix the most outstanding, specially the non-lazy log usage.

### CODE REVIEW

**Comment by joelfranusic-okta** [comment]
Thanks! I'll take a look at this soon. Did you run the included tests to make sure they all passed?

**Comment by diasjorge** [comment]
Sorry actually I didn't. 

Maybe it's possible to setup Travis so they're run for every commit?

**Comment by diasjorge** [comment]
I can confirm that the tests pass locally

**Comment by joelfranusic-okta** [comment]
Thanks for the PR @diasjorge - we normally ask for a signed CLA to accept pull requests, but these look like "[obvious fixes](http://developer.okta.com/cla/)" to me, so I'll accept this PR.

**Pull request merged**
