### PR TITLE
Add support for Okta Verify

### PR DESCRIPTION
**Pull request by sasso**

### CODE REVIEW

**Comment by eedwardsdisco** [comment]
@sasso What ever happened to this? +1 to Okta Verify support for OpenVPN

**Comment by sasso** [comment]
We are using it. Now it's on maintainers @joelfranusic-okta, @gdestuynder to check and merge it in.

**Comment by joelfranusic-okta** [comment]
Hi @eedwardsdisco and @sasso, I'll be taking a look at this next week.

**Comment by eedwardsdisco** [comment]
@joelfranusic-okta That's great Joël! Any progress by chance? I'm evaluating an Okta trial at the moment so my time is limited, but If this could get added (and I believe https://github.com/okta/okta-openvpn/pull/4 as well, as it's related), it would be a huge draw for us to switch to Okta.

Thanks!

**Comment by gdestuynder** [comment]
@sasso sorry, i maintain the upstream Mozilla project, but our codebase seems to be quite different for this part of the code, I suspect my review would not be all that useful (I've not used Okta verify before)

**Comment by sasso** [comment]
@gdestuynder no worries I just pinged you because I saw you contributed

**Comment by joelfranusic-okta** [comment]
@gdestuynder - just wanted to say "thank you" for your contributions. I started out with your code but it diverged pretty quickly. I kept the fork though so it's clear that I based my code on yours. Thanks again!

**Comment by joelfranusic-okta** [comment]
@sasso - thanks for your PR. 

I apologize in advance, because of how critical this code is to security infrastructure, I'm going to be more critical in this review than I usually am.

The main thing that I'd want to see in a new feature would be additional tests that would maintain the "100% coverage" metric that this project has. I realize that this is a high bar since I decided to have the tests based on a mocked API server instead of mocking the API requests in Python.

Secondly, I like the approach you took with the `mfa_check_count` and the `sleep`. I'm just not sure how extensible the `if (factor['factorType'] == "token:software:totp") or (factor['factorType'] == "push"):` line is. I'll have to think about this more though, since I can't think of how I'd structure the logic otherwise.

@eedwardsdisco - as far as timeline goes, I'd like to add support for Okta Verify Push soon. I'm just not sure when that'll land since I need to find some time to get the work done. That said I expect that I'd be able to find time to add this feature on the order of "weeks" and not "months"

I've several other features that I'd like to add, and knowing that support for Okta Verify Push is important is a good motivator to get a new feature out.

@sasso and/or @eedwardsdisco: At this point I'm thinking that I'll add tests for @sasso's code, if I need to do any modifications to the code, would either or both of you be interested or willing to help test the updated code?

**Comment by sasso** [comment]
@joelfranusic-okta that sounds good to me and thank you for jumping in and helping! I'll test when code is ready

**Comment by eedwardsdisco** [comment]
@joelfranusic-okta 100% agreed that proper vetting and testing of this is important, and that's why I'm pushing to have it merged into the official repo rather than simply running off my own build

I am absolutely ready and willing to test it however possible.

The contributions y'all are making toward this are much appreciated.

**Comment by joelfranusic-okta** [comment]
Update: I'm working on this this week.

**Comment by joelfranusic-okta** [comment]
@sasso @eedwardsdisco I've cut a beta release for y'all to try out: https://github.com/okta/okta-openvpn/tree/0_10_1-beta

I've changed the way that the code works pretty substantially from what @sasso wrote. I wanted to make sure that the functionality stayed clear in the code, I also made the timeout and retry parameters configurable. 

Can you try out this version and let me know if it works as expected?

**Comment by eedwardsdisco** [comment]
Hi @joelfranusic-okta appreciate the update.. Unfortunately my trial period has expired and I'm not currently able to test this. It's possible we're going to look into Okta again in a couple months or so when a blocking feature we need may finally be available, so if you happen to make any progress on that by then, it would be a huge win!

Sorry I can't be of more help at the moment.

**Comment by sasso** [comment]
@joelfranusic-okta thank you for the release. We'll try to test this soon!

**Comment by joelfranusic-okta** [comment]
@eedwardsdisco for future reference, I suggest that you get a [Developer Edition of Okta](https://www.okta.com/developer/signup/), which doesn't have any trial period. I hope that your evaluation in a couple of months goes well!

**Comment by joelfranusic-okta** [comment]
I just pushed an update into master that should enable Okta Verify Push support. @sasso or @eedwardsdisco let me know if this update does, or to doesn't work for you!

**Pull request closed without merging**
